export type QuestionCategory =
  | "Physical Plant"
  | "Resident Rights & Policies"
  | "Medication Management"
  | "Staffing & Training"
  | "Emergency Preparedness";

export interface QuestionItem {
  id: number;
  category: QuestionCategory;
  question: string;
}

export const TOP_100_QUESTIONS: QuestionItem[] = [
  // Physical Plant (WAC 388-76-10685~10825) — 20
  { id: 1, category: "Physical Plant", question: "What is the minimum square footage required for a single-occupancy bedroom?" },
  { id: 2, category: "Physical Plant", question: "What is the minimum square footage for a double-occupancy bedroom?" },
  { id: 3, category: "Physical Plant", question: "How many inches of clearance are required around a toilet for wheelchair accessibility?" },
  { id: 4, category: "Physical Plant", question: "What is the required temperature range for hot water at the tap (to prevent scalding and ensure hygiene)?" },
  { id: 5, category: "Physical Plant", question: "What are the requirements for bedroom window egress (size, openable) in a 6-bed AFH?" },
  { id: 6, category: "Physical Plant", question: "How should ramps be designed (slope, handrails, landings) to meet WAC and ADA where applicable?" },
  { id: 7, category: "Physical Plant", question: "What is the minimum width for hallways and corridors used by residents?" },
  { id: 8, category: "Physical Plant", question: "Where must smoke and carbon monoxide alarms be installed, and must they be interconnected?" },
  { id: 9, category: "Physical Plant", question: "What are the requirements for grab bar height and placement in resident bathrooms?" },
  { id: 10, category: "Physical Plant", question: "May a wood countertop be used in the kitchen, and what are the cleaning/sanitation requirements?" },
  { id: 11, category: "Physical Plant", question: "What are the rules for chemical storage (cleaning supplies, medications) in locked vs. accessible areas?" },
  { id: 12, category: "Physical Plant", question: "What minimum lighting (foot-candles) is required in common areas and resident rooms?" },
  { id: 13, category: "Physical Plant", question: "How many exits must each floor have, and what are the requirements for exit signage and illumination?" },
  { id: 14, category: "Physical Plant", question: "What are the requirements for fire extinguisher placement, type, and inspection?" },
  { id: 15, category: "Physical Plant", question: "Is a stovetop fire suppressor or automatic shutoff required for resident-use cooking?" },
  { id: 16, category: "Physical Plant", question: "What are the rules for bedroom door locks (from inside vs. outside) for resident privacy and safety?" },
  { id: 17, category: "Physical Plant", question: "What floor and wall surfaces are acceptable in bathrooms and kitchens (non-absorbent, easy to clean)?" },
  { id: 18, category: "Physical Plant", question: "What are the requirements for hot water heater temperature and mixing valves?" },
  { id: 19, category: "Physical Plant", question: "What ceiling height is required in resident sleeping and living areas?" },
  { id: 20, category: "Physical Plant", question: "What are the requirements for outdoor areas (ramps, steps, handrails) used by residents?" },
  // Resident Rights & Policies (WAC 388-76-10500 series) — 20
  { id: 21, category: "Resident Rights & Policies", question: "When must a resident be given the Notice of Rights?" },
  { id: 22, category: "Resident Rights & Policies", question: "Under what conditions can a resident's funds be managed by the AFH?" },
  { id: 23, category: "Resident Rights & Policies", question: "How must grievances and complaints be documented and responded to?" },
  { id: 24, category: "Resident Rights & Policies", question: "Under what logic can restricted access (e.g., locked front door) be justified for dementia residents?" },
  { id: 25, category: "Resident Rights & Policies", question: "What written information must be provided before admission regarding services and charges?" },
  { id: 26, category: "Resident Rights & Policies", question: "Where must the resident rights poster or notice be displayed?" },
  { id: 27, category: "Resident Rights & Policies", question: "What are the resident's rights regarding privacy, mail, and visitors?" },
  { id: 28, category: "Resident Rights & Policies", question: "When may physical or chemical restraints be used, and what documentation is required?" },
  { id: 29, category: "Resident Rights & Policies", question: "What is the facility's obligation when a resident refuses care or medication?" },
  { id: 30, category: "Resident Rights & Policies", question: "How must the facility handle a resident's request to leave or transfer?" },
  { id: 31, category: "Resident Rights & Policies", question: "What notice must be given before a resident is discharged or asked to leave?" },
  { id: 32, category: "Resident Rights & Policies", question: "What must the admission agreement include regarding fees, services, and termination?" },
  { id: 33, category: "Resident Rights & Policies", question: "How must the facility protect resident confidentiality and records?" },
  { id: 34, category: "Resident Rights & Policies", question: "What are the rules for resident personal property and funds (safekeeping, accounting)?" },
  { id: 35, category: "Resident Rights & Policies", question: "May the facility lock the kitchen at night if a resident complains of hunger? Under what conditions?" },
  { id: 36, category: "Resident Rights & Policies", question: "What is the difference between a negotiated care plan and a standard care plan under WAC?" },
  { id: 37, category: "Resident Rights & Policies", question: "How often must the care plan be reviewed and updated?" },
  { id: 38, category: "Resident Rights & Policies", question: "Who must sign the care plan, and what if the resident or representative refuses?" },
  { id: 39, category: "Resident Rights & Policies", question: "What must the facility do when a resident has a guardian or power of attorney?" },
  { id: 40, category: "Resident Rights & Policies", question: "What are the requirements for house rules and resident responsibilities (posting, content)?" },
  // Medication Management (WAC 388-76-10430) — 20
  { id: 41, category: "Medication Management", question: "What are the Five Rights of medication administration?" },
  { id: 42, category: "Medication Management", question: "How must Schedule II controlled substances be stored and logged?" },
  { id: 43, category: "Medication Management", question: "What constitutes a reportable medication error and how quickly must it be reported?" },
  { id: 44, category: "Medication Management", question: "What documentation is required if a resident self-administers medications?" },
  { id: 45, category: "Medication Management", question: "How should discontinued or expired medications be disposed of and documented?" },
  { id: 46, category: "Medication Management", question: "Who may administer medications in an AFH, and what training is required?" },
  { id: 47, category: "Medication Management", question: "What must the MAR (Medication Administration Record) include for each dose?" },
  { id: 48, category: "Medication Management", question: "How must PRN (as-needed) medications be ordered, documented, and evaluated?" },
  { id: 49, category: "Medication Management", question: "What is required when a resident brings medications from home (outside pharmacy)?" },
  { id: 50, category: "Medication Management", question: "How must medication errors be corrected on the MAR and reported internally?" },
  { id: 51, category: "Medication Management", question: "What storage requirements apply to medications (locked, temperature, separation of internal vs. external)?" },
  { id: 52, category: "Medication Management", question: "When must a pharmacist or nurse review the resident's medications?" },
  { id: 53, category: "Medication Management", question: "What documentation is needed when a resident refuses a dose?" },
  { id: 54, category: "Medication Management", question: "How must medication changes (new, discontinued, dose change) be communicated and documented?" },
  { id: 55, category: "Medication Management", question: "What are the requirements for medication assistance vs. administration (definitions and scope)?" },
  { id: 56, category: "Medication Management", question: "May over-the-counter medications be given without a physician order? Under what conditions?" },
  { id: 57, category: "Medication Management", question: "What must the facility do when a resident is hospitalized (medication reconciliation)?" },
  { id: 58, category: "Medication Management", question: "How long must MARs and medication records be retained?" },
  { id: 59, category: "Medication Management", question: "What is the facility's role when a resident uses a medication organizer or blister pack?" },
  { id: 60, category: "Medication Management", question: "What are the requirements for secure storage of narcotics and other controlled substances (double-lock, etc.)?" },
  // Staffing & Training (WAC 388-76-10130 etc.) — 20
  { id: 61, category: "Staffing & Training", question: "What is the deadline for staff to complete the 75-hour basic training?" },
  { id: 62, category: "Staffing & Training", question: "Who is required to have a TB test, and how often?" },
  { id: 63, category: "Staffing & Training", question: "What qualifications must the AFH administrator have?" },
  { id: 64, category: "Staffing & Training", question: "Why must there always be a designated backup administrator?" },
  { id: 65, category: "Staffing & Training", question: "What are the requirements around background checks and disqualifying crimes?" },
  { id: 66, category: "Staffing & Training", question: "How often must CPR and first aid certifications be renewed?" },
  { id: 67, category: "Staffing & Training", question: "What training must staff complete before providing direct care?" },
  { id: 68, category: "Staffing & Training", question: "What are the staffing ratio or presence requirements (e.g., awake staff at night)?" },
  { id: 69, category: "Staffing & Training", question: "May a new employee provide care before TB results are received?" },
  { id: 70, category: "Staffing & Training", question: "What must be in the employee file (training dates, background check, TB, etc.)?" },
  { id: 71, category: "Staffing & Training", question: "How often must ongoing training or in-services be provided?" },
  { id: 72, category: "Staffing & Training", question: "What are the rules for volunteers and who must have background checks?" },
  { id: 73, category: "Staffing & Training", question: "What happens if an employee's background check reveals a disqualifying crime?" },
  { id: 74, category: "Staffing & Training", question: "Who can count as 'qualified' to administer medications or perform delegated tasks?" },
  { id: 75, category: "Staffing & Training", question: "What documentation must the administrator keep regarding staff competency and training?" },
  { id: 76, category: "Staffing & Training", question: "Are there specific training requirements for dementia care or behavioral health?" },
  { id: 77, category: "Staffing & Training", question: "What is required when the administrator or licensee is absent (delegation, backup)?" },
  { id: 78, category: "Staffing & Training", question: "How must the facility verify that staff have completed required training (certificates, logs)?" },
  { id: 79, category: "Staffing & Training", question: "What are the requirements for reporting abuse, neglect, or exploitation by staff?" },
  { id: 80, category: "Staffing & Training", question: "What are the rules for use of temporary or agency staff in an AFH?" },
  // Emergency Preparedness (WAC 388-76-10470 etc.) — 20
  { id: 81, category: "Emergency Preparedness", question: "How often must fire drills be conducted, and on which shifts?" },
  { id: 82, category: "Emergency Preparedness", question: "What must be included in the emergency food and water supply (quantity, storage)?" },
  { id: 83, category: "Emergency Preparedness", question: "Why must evacuation time for each resident be documented during a drill?" },
  { id: 84, category: "Emergency Preparedness", question: "What must be covered in the written Disaster Plan?" },
  { id: 85, category: "Emergency Preparedness", question: "How should staff be trained and drilled on disaster scenarios?" },
  { id: 86, category: "Emergency Preparedness", question: "What are the requirements for emergency lighting and backup power?" },
  { id: 87, category: "Emergency Preparedness", question: "How often must the disaster plan be reviewed and updated?" },
  { id: 88, category: "Emergency Preparedness", question: "What must be documented after each fire drill (participants, time, issues)?" },
  { id: 89, category: "Emergency Preparedness", question: "What is the facility's obligation during a natural disaster (shelter in place vs. evacuate)?" },
  { id: 90, category: "Emergency Preparedness", question: "What emergency contact information must be kept for residents and families?" },
  { id: 91, category: "Emergency Preparedness", question: "What first aid supplies and equipment must be on hand?" },
  { id: 92, category: "Emergency Preparedness", question: "How must medication refrigeration be handled during a power outage?" },
  { id: 93, category: "Emergency Preparedness", question: "What are the requirements for documenting and reporting an actual emergency or evacuation?" },
  { id: 94, category: "Emergency Preparedness", question: "Must residents participate in every drill, and what if they refuse or are unable?" },
  { id: 95, category: "Emergency Preparedness", question: "What coordination is required with local fire department or emergency services?" },
  { id: 96, category: "Emergency Preparedness", question: "What must the facility do when a resident has special evacuation needs (wheelchair, bedbound)?" },
  { id: 97, category: "Emergency Preparedness", question: "How long must drill and disaster plan records be retained?" },
  { id: 98, category: "Emergency Preparedness", question: "What are the requirements for emergency communication (family notification, DSHS)?" },
  { id: 99, category: "Emergency Preparedness", question: "What maintenance schedule is required for fire alarms, extinguishers, and emergency equipment?" },
  { id: 100, category: "Emergency Preparedness", question: "What is the facility's role in preparing for pandemic or infectious disease outbreak?" },
];
